### ISSUE TITLE
unrecoverable System.DllNotFoundException on initialise

### ISSUE THREAD

**Issue by poppy-io** [Sevii77/aetherment#4]
immediately after installing the plugin via Dalamud, upon running the /aetherment command, and on XIV launch with the plugin, a window appears displaying the following error:
```
Aetherment has encountered an unrecoverable error

System.DllNotFoundException: Unable to load DLL 'C:\users\<USER>\Temp\tik1xqfv.deb\aetherment_core.dll' or one of its dependencies: Module not found (0x8007007E)
    at System.Runtime.InteropServices.NativeLibrary.Load(String libraryPath)
    at System.Runtime.Loader.AssemblyLoadContext.LoadUnmanagedDllFromPath(String unmanagedDllPath)
    at Dalamud.Plugin.Internal.Loader.ManagedLoadContext.LoadUnmanagedDllFromShadowCopy(String unmanagedDllPath) in C:\goatsoft\companysecrets\dalamud\\Plugin\Internal\Loader\ManagedLoadContext.cs:line 371
    at Dalamud.Plugin.Internal.Loader.ManagedLoadContext.LoadUnmanagedDllFromResolvedPath(String unmanagedDllPath, Boolean normalizePath) in C:\goatsoft\companysecrets\dalamud\\Plugin\Internal\Loader\ManagedLoadContext.cs:line 362
    at Dalamud.Plugin.Internal.Loader.ManagedLoadContext.LoadUnmanagedDll(String unmanagedDllName) in C:\goatsoft\companysecrets\dalamud\\Plugin\Internal\Loader\ManagedLoadContext.cs:line 220
    at System.Runtime.Loader.AssemblyLoadContext.ResolveUnmanagedDll(String unmanagedDllName, IntPtr gchManagedAssemblyLoadContext)
    at Aetherment.Aetherment.initialize(Initializers data)
    at Aetherment.Aetherment..ctor()
```

The error seems like a straightforward missing DLL, but I haven't been able to make any progress debugging it on my end via reinstalls or checking available DLLs. `aetherment_core.dll` is present in `~/.xlcore/installedPlugins/Aetherment/0.1.14.0`, and none of the other files mentioned in the above error appear to be missing either.

I'm running v1.1.0.0(1.1.0) of XIVLauncher.Core on NixOS. Are there additional steps to get this plugin working under Linux? Am I missing a dependency?

**Comment by maliciouspastry** [comment]
Aetherment discord has this under aetherment-issues channel.
```
Known Issues
Aetherment fails to install on Linux. This is caused by a library (bcryptprimitives.dll) XIVLauncher.Core doesn't seem to include in its wineprefix. To resolve this issue:
Make sure wine is installed on your system (tested with wine-9.14)
Open a terminal
Enter the following command wine ""; cp "$HOME/.wine/drive_c/windows/system32/bcryptprimitives.dll" "$HOME/.xlcore/wineprefix/drive_c/windows/system32/bcryptprimitives.dll"
A better solution is being looked into.

Aetherment fails to run properly on Linux with the error Fatal error in initialize
This is being looked into, no known fix yet.
```

There was a post about building the DLL under Linux but I don't know if that will help, since its not really linux native its running under Wine. Others can probably give you more information.

I'm stuck waiting for this as well, but I am using Aetheris UI AIO just fine.

**Comment by Shiichibukai** [comment]
> Hello, I'm not a programmer but I've been stuck with the same issue and I figured I may as well contribute on the off-chance it may help. (If it doesn't, then delete at will.) I don't really know which specs you need to see, but I'm using Windows 11 for baseline (Since I saw you discussing Linux above). Seeing the code I can immediately tell that there is some access issues with the folder which impedes its initialization, but beyond that I don't know what could be the issue. ![image](https://private-user-images.githubusercontent.com/189449915/389195795-6040ecbc-1322-4b00-8e34-0cbed317f86f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzNjg2OTUsIm5iZiI6MTczMjM2ODM5NSwicGF0aCI6Ii8xODk0NDk5MTUvMzg5MTk1Nzk1LTYwNDBlY2JjLTEzMjItNGIwMC04ZTM0LTBjYmVkMzE3Zjg2Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyM1QxMzI2MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YTc5YjhjNTgyOTcyMjNjODEwMjU5NDhlMTYwYTAwNzE2NTc1ZjU0MjlmMmE1MmI4YmExMDM2ZWVhMTVmYTFhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Ft-PpT3R_aAl-SyYMgE95Is_kxSuMLalra5kxFdlde8)
> 
> Moreover, I tried disabling and enabling the plugin through Penumbra, but it gives a different issue. ![image](https://private-user-images.githubusercontent.com/189449915/389195908-1d3c1da7-a452-4d5d-9c58-e887f9fb2248.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzNjg2OTUsIm5iZiI6MTczMjM2ODM5NSwicGF0aCI6Ii8xODk0NDk5MTUvMzg5MTk1OTA4LTFkM2MxZGE3LWE0NTItNGQ1ZC05YzU4LWU4ODdmOWZiMjI0OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyM1QxMzI2MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05OWIxZjgzOWVhYmQwYzhjNzRjNDdkMTU0N2MwMDZlZjMyMDUxYTMyNTNlNDNkMzJiODY4ZjUzZTM4ZGJlN2U4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.8Sd3Z1AwzAbiQfDS52MaLli6UFHqftqcy46wCTB00b4)
> 
> Whether this is useful or not I don't know, and I know that plug-ins are very unstable right now, so I don't expect this to be fixed quickly. I just hope that maybe my input may help with something.
> 
> For what its worth, Material UI (the one from Aetherment) has been working fine even after the update, but I decided to delete it as a safety precaution in case anything gets outdated.

Stuff has been falsely flagged by AV's this patch for some reason, could be related to your AV's deleting stuff, and just a general fyi you dont need to delete UI Mods, they will work even when outdated they just wont show the missing textures. You dont need to do anything they will auto update via aetherment when they are updated.

**Comment by Sevii77** [comment]
Should be fixed in 0.20.0 7e50b5118fa256e45bb36b6adce546fa4043f71a
